openapi: 3.1.0
info:
  title: Restroom API
  description: API that allows for listing and reviewing restrooms for some location.
  version: 1.0.0
servers: []
paths:
  /restrooms:
    get:
      summary: Returns list of all restrooms
      operationId: restroom_list
      parameters:
        - name: around
          in: query
          required: true
          description: User location
          schema:
            $ref: "#/components/schemas/Location"
          style: "form"
          explode: true
      responses:
        "200":
          description: Success response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Restroom"
        "400":
          description: "Missing parameters"
        "401":
          description: "Invalid authentication"
    post:
      summary: Submits a restroom
      operationId: restroom_submit
      security:
        - device_key_auth: [ ]
          api_key_auth: [ ]
      requestBody:
        description: "Restroom data to submit"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Restroom"
      responses:
        "200":
          description: "Success response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Restroom"
        "400":
          description: "Missing parameters"
        "401":
          description: "Invalid authentication"

  /restrooms/{restroom_id}/reviews:
    get:
      summary: Returns list of reviews for some restroom
      operationId: review_list
      parameters:
        - in: path
          name: restroom_id
          schema:
            type: string
            format: uuid
          required: true
          description: "UUID of restroom to fetch"
      responses:
        "200":
          description: "Success response"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Review"
        "404":
          description: "Restroom not found"
        "401":
          description: "Invalid authentication"
    post:
      summary: "Submits a review for some restroom"
      operationId: review_submit
      security:
        - device_key_auth: []
          api_key_auth: []
      parameters:
        - in: path
          name: restroom_id
          schema:
            type: string
            format: uuid
          required: true
          description: "UUID of restroom to post review to"
      requestBody:
        description: "Review data to submit"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Review"
      responses:
        "204":
          description: "Success response"
        "400":
          description: "Missing parameters or duplicate review"
        "404":
          description: "Restroom not found"
        "401":
          description: "Invalid authentication"

components:
  securitySchemes:
    api_key_auth:
      type: apiKey
      in: header
      name: X-API-Key
    device_key_auth:
      type: http
      scheme: bearer

  schemas:
    Location:
      type: object
      description: Describes a location by coordinate pair.
      required:
        - longitude
        - latitude
      properties:
        latitude:
          type: number
          format: double
          minimum: -90.0
          maximum: 90.0
        longitude:
          type: number
          format: double
          minimum: -180.0
          maximum: 180.0
      example: {
        "latitude": 33.19012,
        "longitude": 96.99167
      }
    Rating:
      type: number
      format: float
      description: Rating value, typically fixed to 0.5 increments.
      minimum: 0.0
      maximum: 5.0
    Restroom:
      type: object
      description: Describes an instance of a restroom.
      required:
        - id
        - title
        - location
        - review_average
        - review_count
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        title:
          type: string
          example: "Building A, Second Floor"
        location:
          $ref: "#/components/schemas/Location"
        review_average:
          $ref: "#/components/schemas/Rating"
          readOnly: true
        review_count:
          type: integer
          readOnly: true
        distance:
          type: number
          format: double
          readOnly: true
          description: "Distance of restroom from given point, in miles."
        description:
          type: string
          example: "Located on the second floor, this restroom has an uncountable number of entrances."
    Review:
      type: object
      description: Describes a review for some restroom object.
      required:
        - id
        - rating
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        rating:
          $ref: "#/components/schemas/Rating"
        body:
          type: string
        created_at:
          type: string
          format: date-time
          readOnly: true
          description: Creation time of review in ISO8601 format, with fractional seconds.
          example: "2023-11-23T04:05:53.273179Z"

security:
  - api_key_auth: []
  - device_key_auth: []
    api_key_auth: []